package furhatos.app.openaichat.flow

import furhatos.app.openaichat.flow.chatbot.MainChat
import furhatos.app.openaichat.setting.Persona
import furhatos.app.openaichat.setting.hostPersona
import furhatos.app.openaichat.setting.personas
import furhatos.flow.kotlin.*
import furhatos.records.Location

val Greeting = state(Parent) {

    onEntry {
        furhat.attend(users.userClosestToPosition(Location(0.0, 0.0, 0.5)))
        askForAnything("Hi there")
        furhat.say("I'm here to show you an example of what state of the art generative AI can do for a social robot like me.")
        if (furhat.askYN("But before I start, can I tell you some important things about it? ") == true) {
            furhat.say("We are going to use what is commonly known as a large language model to generate what the character should say next. We are going to use the model GPT-3.5 developed by open A I. It's highly creative model that can generate interesting dialogue based on a simple character description. However, this also means that it can occasionally produce text that is inappropriate, factually incorrect or in other ways problematic. And, the experience of hearing such text from a humanoid robot can impact people in unexpected ways, so it's important to use AI responsibly and be mindful of its potential effects.")
            furhat.say("What that said, ")
            if (furhat.askYN("are you ready to try it out?") == true) {
            } else {
                furhat.say("Okay, maybe another time then")
                goto(Idle)
            }
        } else {
            furhat.say("Okay, let's skip right ahead. ")
        }
        goto(ChoosePersona())
    }
}

var currentPersona: Persona = hostPersona

fun ChoosePersona() = state(Parent) {

    val personasWithAvailableVoice = personas.filter { it.voice.first().isAvailable }
    val selectedPersonas = personasWithAvailableVoice.take(3)

    fun FlowControlRunner.presentPersonas() {
        furhat.say("You can choose to speak to one of these characters:")
        for (persona in selectedPersonas) {
            //activate(persona)
            delay(300)
            furhat.say(persona.fullDesc)
            delay(300)
        }
        //activate(hostPersona)
        reentry()
    }

    onEntry {
        presentPersonas()
    }

    onReentry {
        furhat.ask("Who would you like to talk to?")
    }

    onResponse("can you present them again", "could you repeat") {
        presentPersonas()
    }

    for (persona in personas) {
        onResponse(persona.intent) {
            furhat.say {
                random {
                    +"Okay, I will let you talk to ${persona.name}."
                    +"Okay, let's have a chat with ${persona.name}."
                    +"Sure, we can talk to ${persona.name}."
                }
                random {
                    +"And remember, the words of ${persona.name} are generated by GPT - the Generative A I model. Take it for what it is. a demonstration. "
                    +"Remember, everything ${persona.name} says are being generated by GPT - the generative A I model. It's pretty impressive, but could also be problematic. "
                    +"And remember, the dialogue is generated by GPT - the generative A I model, and this is just an example interaction. "
                }
                random {
                    +"When you want to end the conversation, just say, goodbye."
                    +"When it's time to end the conversation, just say, goodbye."
                    +"When you say the word, goodbye, the interaction will stop. "
                }
            }
            currentPersona = persona
            goto(MainChat)
        }
    }
}