#ABNF 1.0 ISO-8859-1;

language en-US;
root $name;

public $name =
Aaron
| Adam
| Andrew
| Anthony
| Antonio
| Benjamin
| Billy
| Bobby
| Bradley
| Brandon
| Brent
| Brett
| Brian
| Bryan
| Carl
| Carlos
| Chad
| Charles
| Christopher
| Corey
| Cory
| Craig
| Curtis
| Daniel
| Danny
| David
| Dennis
| Derek
| Derrick
| Donald
| Douglas
| Edward
| Eric
| Erik
| Frank
| Gary
| George
| Gregory
| Jacob
| James
| Jamie
| Jason
| Jeffery
| Jeffrey
| Jeremy
| Jerry
| Jesse
| Jimmy
| Joel
| John
| Johnny
| Jon
| Jonathan
| Jose
| Joseph
| Joshua
| Juan
| Justin
| Keith
| Kenneth
| Kevin
| Kyle
| Larry
| Marc
| Marcus
| Mark
| Matthew
| Michael
| Nathan
| Nicholas
| Patrick
| Paul
| Peter
| Philip
| Phillip
| Randy
| Raymond
| Richard
| Robert
| Rodney
| Roger
| Ronald
| Russell
| Ryan
| Samuel
| Scott
| Sean
| Shane
| Shawn
| Stephen
| Steve
| Steven
| Terry
| Thomas
| Timothy
| Todd
| Tony
| Travis
| Troy
| Vincent
| William;