#ABNF 1.0 ISO-8859-1;

language en-US;
root $name;

public $name =
Alexander
| Andre
| Andreas
| Axel
| Ben
| Benjamin
| Bernd
| Bjorn
| Christian
| Christoph
| Christopher
| Daniel
| David
| Dennis
| Detlef
| Dieter
| Dirk
| Dominik
| Erik
| Ernst
| Fabian
| Felix
| Finn
| Florian
| Frank
| Gerd
| Gerhard
| Gunther
| Hans
| Harald
| Heiko
| Heinz
| Helmut
| Herbert
| Hermann
| Holger
| Horst
| Jakob
| Jan
| Jannik
| Jens
| Joachim
| Johannes
| Jonas
| Jonathan
| Julian
| Justin
| Jurgen
| Kai
| Karl
| Karsten
| Kevin
| Klaus
| Kurt
| Lars
| Lennart
| Leon
| Linus
| Lothar
| Luca
| Luis
| Lukas
| Manfred
| Marc
| Marcel
| Marco
| Markus
| Martin
| Marvin
| Matthias
| Max
| Maximilian
| Michael
| Mike
| Moritz
| Nick
| Nico
| Niklas
| Nils
| Noah
| Norbert
| Olaf
| Oliver
| Oskar
| Pascal
| Patrick
| Paul
| Peter
| Philipp
| Rainer
| Ralf
| Reinhard
| Rene
| Robert
| Robin
| Rolf
| Rudolf
| Rudiger
| Sascha
| Sebastian
| Siegfried
| Simon
| Stefan
| Sven
| Theodor
| Thomas
| Tim
| Timo
| Tobias
| Tom
| Torsten
| Ulrich
| Uwe
| Walter
| Werner
| Wilfried
| Wolfgang
| Volker;