#ABNF 1.0 ISO-8859-1;

language en-US;
root $name;

public $name =
Adam
| Adrian
| Ahmed
| Albert
| Albin
| Alex
| Alexander
| Alfred
| Ali
| Anders
| Andreas
| Andre
| Anton
| Arne
| Aron
| Arvid
| August
| Axel
| Bengt
| Benjamin
| Bernt
| Bertil
| Bjorn
| Bo
| Carl
| Casper
| Christer
| Christian
| Christoffer
| Claes
| Dan
| Daniel
| David
| Dennis
| Douglas
| Eddie
| Edvin
| Elias
| Elliot
| Emanuel
| Emil
| Erik
| Fabian
| Felix
| Filip
| Fredrik
| Gabriel
| Gunnar
| Gustav
| Goran
| Hampus
| Hannes
| Hans
| Henrik
| Herman
| Hugo
| Hugo 
| Hakan
| Isak
| Jack
| Jacob
| Jakob
| Jan
| Jens
| Jesper
| Jimmy
| Joakim
| Joel
| Johan
| Johannes
| John
| Johnny
| Jonas
| Jonathan
| Josef
| Julius
| Jorgen
| Kalle
| Karl
| Kenneth
| Kent
| Kevin
| Kim
| Kjell
| Kurt
| Lars
| Leif
| Lennart
| Leo
| Leon
| Liam
| Linus
| Love
| Lucas
| Ludvig
| Magnus
| Marcus
| Martin
| Mats
| Mattias
| Max
| Melker
| Melvin
| Mikael
| Mohamed
| Niklas
| Nils
| Nils 
| Noah
| Oliver
| Olle
| Olle 
| Olof
| Oscar
| Oskar
| Patrik
| Per
| Peter
| Petter
| Preben
| Pontus
| Rasmus
| Rickard
| Robert
| Robin
| Roger
| Roland
| Rolf
| Samer
| Samuel
| Sebastian
| Simon
| Stefan
| Sten
| Stig
| Sven
| Theo
| Theodor
| Thomas
| Tim
| Tobias
| Tom
| Tommy
| Tony
| Torbjorn
| Ulf
| Viktor
| Vincent
| Wilhelm
| William;