#ABNF 1.0 ISO-8859-1;

language en-US;
root $name;

public $name =
Agnes
| Agneta
| Alexandra
| Alice
| Alicia
| Alma
| Alva
| Amanda
| Amanda 
| Andrea
| Anette
| Angelica
| Anita
| Ann
| Anna
| Ann-Christin
| Anneli
| Annie
| Annika
| Ann-Marie
| Astrid
| Barbro
| Beatrice
| Berit
| Birgit
| Birgitta
| Britt
| Britta
| Britt-Marie
| Camilla
| Carina
| Carolina
| Caroline
| Cassandra
| Cecilia
| Charlotte
| Cornelia
| Daniella
| Ebba
| Elin
| Elin 
| Elina
| Elisabeth
| Ella
| Ella 
| Ellen
| Ellinor
| Elsa
| Elvira
| Emelie
| Emilia
| Emma
| Emmy
| Erika
| Eva
| Evelina
| Fanny
| Felicia
| Filippa
| Frida
| Gabriella
| Gerd
| Girls
| Gun
| Gunilla
| Gunnel
| Hanna
| Helen
| Helena
| Hilda
| Ida
| Ida 
| Inga
| Ingela
| Inger
| Ingrid
| Irene
| Isabella
| Isabelle
| Isabelle 
| Jasmine
| Jennifer
| Jenny
| Jessica
| Johanna
| Jonna
| Josefin
| Josefine
| Julia
| Kajsa
| Karin
| Katarina
| Kerstin
| Klara
| Kristina
| Lena
| Lina
| Linda
| Linn
| Linnea
| Lisa
| Lisbeth
| Louise
| Lovisa
| Madeleine
| Maj
| Maja
| Malin
| Malvina
| Margareta
| Maria
| Marianne
| Marie
| Matilda
| Melissa
| Michelle
| Mikaela
| Miranda
| Moa
| Moa 
| Molly
| Mona
| Monica
| Nathalie
| Nellie
| Nicole
| Nora
| Olivia
| Pernilla
| Pia
| Rebecka
| Ronja
| Rut
| Saga
| Sandra
| Sanna
| Sara
| Selma
| Siv
| Sofia
| Sofie
| Sonja
| Stina
| Susanne
| Thea
| Therese
| Tilda
| Tilde
| Tova
| Tove
| Tuva
| Ulla
| Ulrika
| Vanessa
| Vendela
| Vera
| Victoria
| Viktoria
| Wilma
| Yvonne;