#ABNF 1.0 ISO-8859-1;

language en-US;
root $name;

public $name = Alicia
| Allison
| Amanda
| Amber
| Amy
| Andrea
| Angela
| Ann
| Anna
| April
| Barbara
| Brandy
| Brenda
| Carrie
| Catherine
| Cheryl
| Christina
| Christine
| Christy
| Crystal
| Cynthia
| Dana
| Danielle
| Dawn
| Deborah
| Debra
| Denise
| Diana
| Donna
| Elizabeth
| Emily
| Erica
| Erin
| Gina
| Heather
| Heidi
| Holly
| Jacqueline
| Jamie
| Jennifer
| Jessica
| Jill
| Julie
| Karen
| Katherine
| Kathleen
| Kathryn
| Kelly
| Kimberly
| Kristen
| Kristin
| Kristina
| Laura
| Leslie
| Linda
| Lisa
| Lori
| Maria
| Mary
| Megan
| Melanie
| Melinda
| Melissa
| Michele
| Michelle
| Misty
| Monica
| Nancy
| Nicole
| Pamela
| Patricia
| Paula
| Rachel
| Rebecca
| Renee
| Rhonda
| Robin
| Sandra
| Sara
| Sarah
| Shannon
| Sharon
| Sherry
| Stacey
| Stacy
| Stephanie
| Susan
| Tamara
| Tammy
| Tanya
| Tara
| Teresa
| Theresa
| Tiffany
| Tina
| Tonya
| Tracy
| Valerie
| Veronica
| Wendy;