#ABNF 1.0 ISO-8859-1;

language en-US;
root $name;

public $name =
Alexandra
| Alina
| Amelie
| Andrea
| Angela
| Angelika
| Anja
| Anke
| Ann
| Anna
| Annika
| Antonia
| Astrid
| Barbara
| Beate
| Bettina
| Bianca
| Birgit
| Brigitte
| Britta
| Caroline
| Celina
| Celine
| Chiara
| Christa
| Christiane
| Christina
| Christine
| Claudia
| Cornelia
| Dagmar
| Daniela
| Doris
| Elke
| Emilie
| Franziska
| Gisela
| Gudrun
| Hannah
| Hannelore
| Heidemarie
| Heidi
| Heike
| Helga
| Ingrid
| Isabel
| Jacqueline
| Jana
| Janina
| Janine
| Jasmin
| Jennifer
| Jessica
| Johanna
| Jule
| Julia
| Jutta
| Karin
| Katharina
| Katja
| Katrin
| Kerstin
| Kim
| Kirsten
| Klara
| Kristin
| Lara
| Laura
| Lea
| Lena
| Leonie
| Lilli
| Lina
| Lisa
| Luisa
| Maike
| Maja
| Manuela
| Margret
| Margrit
| Maria
| Marie
| Marion
| Marlies
| Martina
| Melanie
| Melina
| Merle
| Mia
| Michaela
| Michelle
| Monika
| Nadine
| Natalie
| Nele
| Nicole
| Nina
| Petra
| Pia
| Regina
| Renate
| Rita
| Sabine
| Sabrina
| Sandra
| Sarah
| Saskia
| Sigrid
| Silke
| Silvia
| Simone
| Sonja
| Sophia
| Sophie
| Stefanie
| Susanne
| Svenja
| Tanja
| Ulrike
| Ursula
| Ute
| Vanessa
| Yvonne;